sudo: required

services:
- docker

language: scala

scala:
- 2.12.6

env:
  global:
  - secure: Z084dCwYIhvmZuQ+PxZqbA7Hy9pBQRUatI/Mo/m2DsgZ2u5NAYCfns50MbR+qs0/hHnJ+vNTXoVRYSP3vyWNJWPhPh6FNj63ZcTpOI3bPs86x6EFT5bdXX9P2moJ/b0Ui0QlV7INYrsaxqTeRTonRAPDPTVar02hq2YJLrGKuoshVis0y6rC4/9dU+zbzveccOfAvR7w68JDS5VdN4XBihQI4HEr/RdLSrjX6xJCjPZD6UtdjAa3LIy3DmQzDMzuOUwYBxUwknVtxWibiWZpHk/CXg8qTbSJZlbCzrwOLjFwUYqTCpE51myRHgxi/cMJNuCmKY7ZbWKqKKJwCo82YulNpKjZPb0MTf45jCWueumapeYN84XlX02hkGQe+sQ5gWOmCS2JaFxEG8tdQ+gHeQ+8743gFPL3ZkU79QDKNYy26O92j0LQ5D0uqz3VVLc/nGgFB62QOu2yk4ByFNZCk/IsVrcIeGBbpfBb357nLgaUCgdJEv5/0gibSHvbRtFi/GiTHabMYRFSrPiwrxHAEXKVPqkGJHYYYgmVi61wFq9J/DKEasmPf998EOHRuPRjTy44Wzt0cqcDRgmYfGrhySyuxoVnCfnfOlkuBzkLgxC1tDVYTM3B9zyFjbsH8Xrb5+x8NylKMZq1orVEAMbKFAVDuZAjsVn2Yxotig9DKVs=
  - secure: BzBQNpvHGnwfLOZ1eHMZBih9R/6fPA5B8C7qsUrCOjtF7eH0nebepBMM32iFwnpj+X10QihRZky1kxzwW4JovB5ApQ1QEd2Nf3IzTKCvLCEO2jDIXMEMdbwgb2pYUlotFIYWZnnMsIjH+KO2/jbhAPHs8CXtO7BoleT/j1d3Hgh5VZoUkNd2Aj9Jyu0wsCtD7qakMo1jrlgNUKglHGPg9FcxMkF6iFjdPjYK4gZdKwUlmxlb+W0Olc/nJs74/xd/woKuWbI5ORDAmo/yfIPTo5uSvn07ZblSFkBHsFHzdyPoxucuV2P+AuZdrviJOW2uDjSaEIr0Z9mPOefPmzzPO9HxUBoK2FUen5BsG/fL7plOqaerp4QdZyOToTSi+0hRlWNe37zzLoi2mcn8vRjnI1EtqoxO+eBLFGWJhnA6Fe845oHxySMajLj3ogb+7WUAquPyNaOfQ24rok3VnqYKWxCj6+QDnOkfaZ99o2MkVSscWaIaMk+ZZ1Dr7aq82jCAjoJGt4+JQAoB8Gbo+Q3gtJd2zjYo4YQUJSLOEqUyROiMMyGLfgKDqt1ocHxyZJDO71PKW4lwRfB4EQpj1cw5x26iIAa82/6zVY6VEzYFfcIKfEhMa7yfeH1BdHqhGtycDeHw5ajZUKclUWG6JIjLhnEjYSdqHtC1UHa3uB5itLU=

before_script:
- echo "Starting dependent containers for testing"
- docker-compose up -d
- echo "Compile the project while containers are starting up"
- sbt ++$TRAVIS_SCALA_VERSION clean compile
- echo "Wait for containers to be up and running"
- bash waitForContainerSetup.sh

script:
- sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash)
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin;
  sbt docker:publish;

after_script:
- docker-compose kill
