# In our Travis builds we run the regular tests for Airlock on every push (all branches and PRs)
# The integration tests that require all dependent docker containers to be started, will only be run on PRs and master.
# This is done since the starting of all docker containers (mainly Atlas and Ranger) takes a lot of time.
# Coverage is only reported on PRs and master as only then the full coverage with integration tests is known.

sudo: required

services:
- docker

language: scala

scala:
- 2.12.8

env:
  global:
  - DOCKER_REPO: wbaa/airlock
  - secure: "ml6+GmfUf0Zg5WuT/yxiocDpfJDHsfVkY6ufn5tWQFemV+pBV/EhfgtQiMOP/FKml/2tDExnuoYOfB+ZJgGWyD+gjCxT5y+Q4GSNaN6PrZ0YgfhtClRkid4SAgYag/xW6rKjjmMxfeRCGZIwtjnSJk5tZOJ/Dt/2uDsWO5s7iGQBlYP81+s1u6PVwti9Eoez+Tzb9a6mXwtzUpeRq/wqL2xoOZha6gaYOI1//t2JsvoQZMJHcB9l4qju1tclhQU5XhLag6Zdl9b0QkRAlV4jE+rojxrFVaK0rrLGIeoCTnS+cD72sxniVF1vJGTyc40SAsIXlOpBTI0AtueBBuhvowS2nC83Kk4ILqDlikEav2gR14ldTXHtTbJ1DlTZL7i+MCZQuBOd7URW/8pYSW6F3O0gTQ94Opbr08B4RH26+WVe+cjqiOC1OXOlRcfWi5VCGO5E3n0GL1fOV/5RP05C69eiV1oazoQj1afwcEpIt0Baw4SFNARSA4xfjPPSjSSzYUhF9awUJU7tGjQVZjL41cBDSetiL8cMzXjDQVmL/1qPWkxILVYjFHCfXK/7H/WHk+2STu5ufdvHqu+02XZmqlrRnBKoTOAlDULm8Dl5c6HRm4JQxZFG4znjmaif2vWJcHS8m780CEfGd7+3xj0dX5jLCiK7jsR4QUYd55+4/A0="
  - secure: "etmoi333s/6UzoUzYOib2MX21CqnkwBXJUQWuGjIIRsguaGU2wkMdGD7VJhc7Q58Wz+KmGx/NXhNl1rmfGyseuuo0NteXo1mjAKs0lMyxcUqEZsHt43rlNTl9LlITIAaX/0o3ur0YhKYDzPgekZZskHkK47eQIFQzqmjl7ig5SlxO7QGKhY261YDrGc6e2W1Nnz5wPjpyu0syCYPNstBJWU90v1Qh1IJLmvujaF5kf/CJMKCa/Hb4K4M7DTJtqU9bjjRqNpgqp8tA2cJrUGZZ7A1h4NRlp4Rxbk3+6pGyeE93EtCjSDtztuDaUs0Qsjn0bVZ/2kMMR+RPO5TSTVm1v/0A/+PyFqV34tK8y4P8cToMf4CYVBbUut90W1Oa7DYQibJe00Xn2wu6R5trjW/3ttP6qwYXXepIuQRTMb2YJHm8zUMb1dmuDmvMJP6eBvvYfOt/jtdVHsGbz+PQxnfU5m+ReHs3eabefUltKrCwb7/LKNbLraC4qBJVawjq3kYvi+C8pELnloEn4erc6nfObPiZMm8HSnAtHz6tOXnXBM+bUmLzfBvz/DAt2fWk1EHjX0hxOQSBEp6pTCJMi1+UU5bOTbfhK1rb5XYgEAZ6Th2LoXDgwbqXQRrapOtDirdwqIGdrZcLdGDyNqkU0C4N91r+h26j8OfajN7uNOsJJ8="

before_script:
- echo "Running pipeline for branch ${TRAVIS_BRANCH}"
- if [ "$TRAVIS_PULL_REQUEST" != "false" -o "${TRAVIS_BRANCH}" == "master" ]; then
    echo "Starting dependent containers for testing";
    docker-compose up -d atlas ;
    docker-compose up -d ceph postgres-server mariadb ranger-admin airlock-sts keycloak;
    pip install --user awscli;
    echo "Compile the project while containers are starting up";
    sbt ++$TRAVIS_SCALA_VERSION clean compile;
    echo "Wait for containers to be up and running";
    bash waitForContainerSetup.sh;
    bash setupS3Env.sh;
  fi

script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" -o "${TRAVIS_BRANCH}" == "master" ]; then
    echo "Running pipeline for branch ${TRAVIS_BRANCH} (This is a PR or master build, so it:test will be run)";
    sbt ++$TRAVIS_SCALA_VERSION clean coverage test it:test coverageReport;
  else
    echo "Running pipeline for branch ${TRAVIS_BRANCH} (This is not a PR or master build so only test will be run)";
    sbt ++$TRAVIS_SCALA_VERSION clean test;
  fi

after_success:
- if [ "$TRAVIS_PULL_REQUEST" != "false" -o "${TRAVIS_BRANCH}" == "master" ]; then
    bash <(curl -s https://codecov.io/bash);
  fi
- export AIRLOCK_VERSION="${TRAVIS_BRANCH/\//_}"
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- if [ "${TRAVIS_BRANCH}" != "master" ]; then
    echo "Build image for with name $DOCKER_REPO:$AIRLOCK_VERSION";
    sbt clean docker:publish;
  fi
- if [ -n "$TRAVIS_TAG" ]; then
    docker tag $DOCKER_REPO:$AIRLOCK_VERSION $DOCKER_REPO:latest;
    docker push $DOCKER_REPO:latest;
  fi

after_script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" -o "${TRAVIS_BRANCH}" == "master" ]; then
    docker-compose down;
  fi
